지니 top 200

한페이지당 50순위씩 \
https://www.genie.co.kr/chart/top200?ditc=D&ymd=20230417&hh=15&rtm=Y&pg=1 \
https://www.genie.co.kr/chart/top200?ditc=D&ymd=20230417&hh=15&rtm=Y&pg=2 \

pg for문으로 돌리기

In [15]:
import requests
from bs4 import BeautifulSoup
import re  # 정규표현식
import pandas as pd
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'}
base="https://www.genie.co.kr/chart/top200?ditc=D&ymd=20230417&hh=15&rtm=Y&pg="
pg = ['1','2','3','4']

In [130]:
line = []

for i in range(len(pg)):

    url = base + pg[i]
    html = requests.get(url, headers = headers).text
    soup = BeautifulSoup(html, 'html.parser')

    bestList = soup.select('tbody > tr')

    for j in range(len(bestList)):

        try:
            rank = int(bestList[j].find('td', 'number').contents[0].strip())
        except:
            rank = -999

        try:
            subj = bestList[j].find('td', 'info').find('a', 'title').contents[-1].strip()
        except:
            subj = "---"
        
        try:
            arts = bestList[j].find('td', 'info').find('a', 'artist').contents[-1].strip()
        except:
            arts = "---"
        
        try:
            albm = bestList[j].find('td', 'info').find('a', 'albumtitle').contents[-1].strip()
        except:
            albm = '---'
        #print(albm)

        line.append([rank, subj, arts, albm])


df = pd.DataFrame(line, columns=['순위', '제목', '아티스트', '앨범'])

df

      순위                    제목         아티스트                                 앨범
0      1                  I AM    IVE (아이브)                           I've IVE
1      2                Kitsch    IVE (아이브)                           I've IVE
2      3                     꽃   지수 (JISOO)                                 ME
3      4                 Ditto     NewJeans                     NewJeans 'OMG'
4      5             CHRISTIAN    Zior Park  WHERE DOES SASQUATCH LIVE? PART 1
..   ...                   ...          ...                                ...
195  196                스티커 사진         21학번                             스티커 사진
196  197            BETELGEUSE        Yuuri                         BETELGEUSE
197  198         Way Back Home    숀 (SHAUN)                               Take
198  199  GANADARA (Feat. 아이유)          박재범                           GANADARA
199  200               언제나 사랑해  케이시 (Kassy)               조영수 리메이크 프로젝트 Part.2

[200 rows x 4 columns]

In [129]:
df.to_csv("../daou/지니top200")